site_name: Maths Wiki
site_url: https://maths.wiki
site_author: Pranshu Gaba
site_description: >-
  A fun and exciting resource for learning Maths and Computer Science!

# Repository
repo_name: pranshugaba/maths-wiki
repo_url: https://github.com/pranshugaba/maths-wiki
edit_uri: "edit/master/docs"

# Copyright
copyright: '&copy; 2021 Maths Wiki <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA</a>'

# Configuration
theme:
  name: material
  # name: null
  # custom_dir: mkdocs-material/material

  extra:
    manifest: manifest.webmanifest

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    # - header.autohide
    # - toc.integrate #left sidebar might become too long
    # - instant #this breaks math rendering
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Source Sans Pro
    code: Roboto Mono
  icon:
    logo: material/pi
    admonition:
      warning: octicons/alert-16
      abstract: octicons/filter-16
      success: octicons/check-circle-16
      failure: octicons/x-circle-16
      info: octicons/note-16
      note: octicons/checklist-16
      question: octicons/question-16
      tip: octicons/light-bulb-16
      example: octicons/list-unordered-16
      quote: octicons/quote-16
      bug: octicons/beaker-16
      danger: octicons/zap-16
    # favicon: images/favicon.ico

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
  - macros
      # include_dir: snippets
  - awesome-pages:
      filename: .index
      collapse_single_pages: false
      strict: true
  - redirects:
      redirect_maps:
        'about/': 'about/maths-wiki.md'
  # - toc-sidebar
  # - tooltipster-links
  # - mk2pdf-export
  # - enumerate-headings:
  #     strict: true
  # - add-number:
  #     strict_mode: False
  #     order: 1


# Customization
extra:
  generator: true
  social:
   - icon: fontawesome/brands/github
     link: https://github.com/pranshugaba/maths-wiki
     name: Maths Wiki on GitHub
   - icon: fontawesome/brands/twitter
     link: https://twitter.com/mathswiki
     name: Maths Wiki on Twitter


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - smarty
  - toc:
      # permalink: 🔗
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.extra
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.progressbar:
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.0/katex.min.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.0/contrib/auto-render.min.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.0/contrib/render-a11y-string.min.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.0/contrib/mathtex-script-type.min.js 
  - js/svg-inject.js

extra_css:
  - css/img.css
  - css/svg.css
  - css/custom.css
  - css/progress.css
  - css/anim.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.0/katex.min.css 

google_analytics:
  - 'UA-164642577-2'
  - auto

