site_name: Maths Wiki
site_url: https://maths.wiki
site_author: Pranshu Gaba
site_description: >-
  A collection of maths notes.

# Repository
# repo_name: pranshugaba/maths-wiki-src
# repo_url: https://github.com/pranshugaba/maths-wiki-src
# edit_uri: ""

# Copyright
copyright: '&copy; 2021 Maths Wiki <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA</a>'

# Configuration
theme:
  # name: material
  name: null
  custom_dir: mkdocs-material/material

  extra:
    manifest: manifest.webmanifest

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    # - toc.integrate #left sidebar might become too long
    # - instant #this breaks math rendering
  palette:
    scheme: default
    primary: white
    accent: blue
  font:
    text: Source Sans Pro
    code: Roboto Mono
  icon:
    logo: material/pi
    # favicon: images/favicon.ico

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
  - macros
      # include_dir: snippets
  - awesome-pages:
      filename: .index
      collapse_single_pages: false
      strict: true
  # - markdownmermaid
  # - toc-sidebar
  # - tooltipster-links
  # - mk2pdf-export
  # - enumerate-headings:
  #     strict: true
  # - add-number:
  #     strict_mode: False
  #     order: 1


# Customization
extra:
 social:
   - icon: fontawesome/brands/github
     link: https://github.com/pranshugaba/maths-wiki-src
     name: Maths Wiki on GitHub
   - icon: fontawesome/brands/twitter
     link: https://twitter.com/mathswiki
     name: Maths Wiki on Twitter

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      # permalink: 🔗
      permalink: false
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.extra
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


extra_javascript:
  # - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  # - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.8.0/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.0/katex.min.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.0/contrib/auto-render.min.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.0/contrib/render-a11y-string.min.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.0/contrib/mathtex-script-type.min.js 

extra_css:
  - css/img.css
  - css/custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.0/katex.min.css 
  
google_analytics:
  - 'UA-164642577-2'
  - auto

